# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 9, 10, 10, 11, 25, 948426, tzinfo=utc))),
            ],
        ),
    ]
