# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 10, 10, 25, 39, 926583, tzinfo=utc)),
        ),
    ]
